{{- if and .Values.serviceAccount.create (eq .Values.provider "local") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nosql.serviceAccountName" . }}
  labels:
    {{- include "nosql.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
